build:
  environment:
    python: 3.11
  nodes:
    tests:
      dependencies:
        before:
          - "pip install --upgrade 'tox>=4.6,<5'"
          - "pip install --upgrade 'poetry-core>=1.4,<2'"
    analysis:
      project_setup:
        override:
          - true
      tests:
        override:
          - py-scrutinizer-run
          - pylint-run
checks:
  python:
    code_rating: true
    duplicate_code: true
