build:
  environment:
    python: 3.11.8
  nodes:
    analysis:
      project_setup:
        override:
          - true
      tests:
        override:
          - py-scrutinizer-run
          - pylint-run
checks:
  python:
    code_rating: true
    duplicate_code: true
